name: Go CI/CD

on:
  push:
    branches: [ "master" ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Insall SSH key
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.SSH_KEY }}
      
      - name: check user
        run: whoami

      - name: Deploy and Restart
        run: |
          ssh -o StrictHostKeyChecking=no ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} /bin/bash << 'EOF'
          set -euxo pipefail

          DEPLOY_DIR="/opt/server-bot"
          cd "$DEPLOY_DIR"

          git fetch --all
          git reset --hard origin/master
          git clean -fd

          rm tgbot
          go mod tidy
          go build -o tgbot main.go || { echo "Ошибка сборки"; exit 1; }
          

          kill $(cat /root/tgbot/bot.pid) 2>/dev/null || true

          nohup ./tgbot > bot.log 2>&1 & echo $! >| bot.pid
          echo "Бот перезапущен"
          EOF
