name: Go CI/CD

on:
  push:
    branches: [ "master" ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: install SSH key
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.SSH_KEY }}

      - name: cicd
        run: |
          ssh -o StrictHostKeyChecking=no ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} << 'EOF'
          cd /opt/server-bot
          git pull origin master
          sleep 5
          rm -f tgbot
          go mod tidy
          export GITHUB_TOKEN='$GITHUB_TOKEN'
          go build -o tgbot main.go
          kill $(cat /opt/server-bot/bot.pid) 2>/dev/null || true
          nohup /opt/server-bot/tgbot > bot.log 2>&1 & echo $! >| bot.pid
          EOF
        env:
          TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

          