name: Go CI/CD

on:
  push:
    branches: [ "master" ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.21'

      - name: Build
        run: GOOS=linux GOARCH=amd64 go build -o tgbot

      - name: install SSH key
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.SSH_KEY }}

      - name: cicd
        run: |
          ssh -o StrictHostKeyChecking=no ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} << 'EOF'
          cd /opt/server-bot
          git pull origin master
          sleep 5
          rm -f tgbot
          go mod tidy
          sleep 5
          go build -o tgbot main.go
          kill $(cat /opt/server-bot/bot.pid) 2>/dev/null || true
          TELEGRAM_TOKEN='${{ secrets.TELEGRAM_TOKEN }}' GITHUB_TOKEN='${{ secrets.GITHUB_TOKEN }}' nohup ./tgbot > bot.log 2>&1 & echo $! >| bot.pid
          EOF
          